export const CUSTOMERS_LIST_REQUEST = 'CUSTOMERS_LIST_REQUEST'
export const CUSTOMERS_LIST_SUCCESS = 'CUSTOMERS_LIST_SUCCESS'
export const CUSTOMERS_LIST_FAIL = 'CUSTOMERS_LIST_FAIL'


export const CUSTOMER_ADD_REQUEST = 'CUSTOMER_ADD_REQUEST'
export const CUSTOMER_ADD_SUCCESS = 'CUSTOMER_ADD_SUCCESS'
export const CUSTOMER_ADD_FAIL = 'CUSTOMER_ADD_FAIL'

export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST'
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS'
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL'


export const CUSTOMER_DETAIL_REQUEST = 'CUSTOMER_DETAIL_REQUEST'
export const CUSTOMER_DETAIL_SUCCESS = 'CUSTOMER_DETAIL_SUCCESS'
export const CUSTOMER_DETAIL_FAIL = 'CUSTOMER_DETAIL_FAIL'

export const CUSTOMER_UPDATE_RESET = 'CUSTOMER_UPDATE_RESET'

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST'
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS'
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL'