export const SUPPLIERS_LIST_REQUEST = 'SUPPLIERS_LIST_REQUEST'
export const SUPPLIERS_LIST_SUCCESS = 'SUPPLIERS_LIST_SUCCESS'
export const SUPPLIERS_LIST_FAIL = 'SUPPLIERS_LIST_FAIL'


export const SUPPLIER_ADD_REQUEST = 'SUPPLIER_ADD_REQUEST'
export const SUPPLIER_ADD_SUCCESS = 'SUPPLIER_ADD_SUCCESS'
export const SUPPLIER_ADD_FAIL = 'SUPPLIER_ADD_FAIL'

export const SUPPLIER_UPDATE_REQUEST = 'SUPPLIER_UPDATE_REQUEST'
export const SUPPLIER_UPDATE_SUCCESS = 'SUPPLIER_UPDATE_SUCCESS'
export const SUPPLIER_UPDATE_FAIL = 'SUPPLIER_UPDATE_FAIL'


export const SUPPLIER_DETAIL_REQUEST = 'SUPPLIER_DETAIL_REQUEST'
export const SUPPLIER_DETAIL_SUCCESS = 'SUPPLIER_DETAIL_SUCCESS'
export const SUPPLIER_DETAIL_FAIL = 'SUPPLIER_DETAIL_FAIL'

export const SUPPLIER_UPDATE_RESET = 'SUPPLIER_UPDATE_RESET'

export const SUPPLIER_DELETE_REQUEST = 'SUPPLIER_DELETE_REQUEST'
export const SUPPLIER_DELETE_SUCCESS = 'SUPPLIER_DELETE_SUCCESS'
export const SUPPLIER_DELETE_FAIL = 'SUPPLIER_DELETE_FAIL'