# Generated by Django 3.2.4 on 2021-11-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='memo',
        ),
    ]
