# Generated by Django 3.2.4 on 2022-01-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
